{% set version = "2.7.2" %}

package:
  name: openalea.lpy
  version: {{ version }}

source:
  path: ..

about:
  home: https://github.com/openalea/lpy
  license: Cecill-C
  summary: L-Py is a simulation software that mixes L-systems construction with the Python high-level modeling language.

build:
  preserve_egg_dir: True
  number: 1
  features:
    - vc9         [win and py27]
    - vc14        [win and py37]
  track_features:
    - vc9         [win and py27]
    - vc14        [win and py37]

requirements:
  build:
    - cmake >=3.2.0
    - binutils_impl_linux-64<2.31.0 # [linux]
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libXt-devel') }}           # [linux]
    - {{ cdt('libICE-devel') }}          # [linux]
    - {{ cdt('libuuid-devel') }}         # [linux]
    - {{ cdt('libSM-devel') }}           # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - python=3.7
    - qt >=5.9.0
    - boost-cpp
    - py-boost
    - setuptools
#   - openalea.deploy
    - cmake >=3.12.0
    - openalea.plantgl
    - pyqt
  host:
    - openalea.plantgl
    - boost-cpp
    - python=3.7
    - py-boost
  run:
   - python=3.7
   - openalea.plantgl
   - boost-cpp
   - qt >=5.9.0
   - pyqt
   - ipython
#  - qtconsole
   - pyopengl
#  - pyqglviewer
   - vs2008_runtime [win and py27]
   - vs2015_runtime [win and py37]
# test:
#   requires:
#     - nose
#   imports:
#     - openalea.lpy
#   source_files:
#     - test/
#     - share/
#   commands:
#     - nosetests -v -I test_predecessor_at_scale.py -I test_ui.py [unix]
#     - nosetests -v -I test_predecessor_at_scale.py -I test_ui.py -I test_axialtree.py -I test_successor_at_scale.py [win]
